version: "2"
services:

  funda:
    build: .
    env_file: .env
    container_name: funda
    ports:
      - '${APP_PORT}:8080'
    volumes:
          - ./:/go/src/funda
    networks:
      scraper:
        aliases:
          - funda

networks:
  scraper:
    external: true
    driver: bridge